title: 'elasticseatch'
description: '开坑啦 elasticseatch'
themeConfig:
  # 导航栏
  # nav:
  #   - text: "入门"
  #     link: "/base/intro"
  #   - text: "应用"
  #     link: "/app/"
  #   - text: "深入"
  #     link: "/deep/"
  
  # 侧边栏
  sidebar:
    - title: 入门
      collapsable: false
      sidebarDepth: 1
      children:
        - /base/intro
        - /base/install
        - /base/concepts
        - /base/data-source